[workspace]
resolver = "2"
members = [
    "shared_protocol_objects",
    "mcp_rust_host_one_file", 
    "web_scrape_mcp",
]

[workspace.dependencies]
env_logger = "0.10"
console = "0.15"

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1